# Generated by Django 4.2 on 2023-04-26 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='call_time',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('blocked', 'blocked'), ('waiting', 'waiting')], default='waiting', max_length=10),
        ),
    ]
