# Generated by Django 4.2 on 2023-04-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_announcemoderation_announce_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phoneNumber',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('blocked', 'blocked'), ('waiting', 'waiting')], max_length=7),
        ),
    ]
