# Generated by Django 4.2 on 2023-04-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_call_time_user_phone_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
