# Generated by Django 4.2 on 2023-04-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='announcemoderation',
            old_name='announce_id',
            new_name='announce',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='Region',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announce_state',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_name',
        ),
        migrations.AddField(
            model_name='announcement',
            name='state',
            field=models.CharField(choices=[('draft', 'draft'), ('moderate', 'moderate'), ('rejected', 'rejected'), ('active', 'active')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
